name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Установка необходимых зависимостей
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgtest-dev
        libsqlite3-dev
        make gcc

    # Шаг 3: Сборка проекта
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    # Шаг 4: Запуск тестов
    - name: Run tests
      run: |
        cd build
        ctest --verbose
